# fly.toml app configuration file generated for exploring-beam-community on 2025-01-07T05:54:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'exploring-beam-community'
primary_region = 'mad'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'exploring-beam-community.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[services]]
  protocol = ''
  internal_port = 0
  ports = []

  [services.concurrency]
    type = 'connections'
    hard_limit = 300
    soft_limit = 150

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
